### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hmsjy2017** [cayzlh/git-img-repository#1]
用GitHub做图床，可使用[jsDelivr](https://cdn.jsdelivr.net/)的免费CDN，提高访问速度，解决raw被墙的问题

**Comment by cayzlh** [comment]
> 用GitHub做图床，可使用[jsDelivr](https://cdn.jsdelivr.net/)的免费CDN，提高访问速度，解决raw被墙的问题

博客里都用了的
